src/print_results/matematica/matematica.h File Reference
Functions
int min (int a, int b)
int max (int a, int b)
int pred (int a)
int succ (int a)
int sum (int a, int b)
int subtract (int a, int b)
int product (int a, int b)
int factorial (int n)
Function Documentation
int factorial (int n)
Calcola il prodotto fattoriale del parametro Richiama la funzione prodotto
Parameters
n
Returns
Definition at line 61 of file matematica.c.
References factorial(), pred(), and product().
Referenced by factorial().
int max (int a, int b)
Restituisce il maggiore dei due parametri
Parameters
a
b
Returns
Definition at line 16 of file matematica.c.
int min (int a, int b)
Restituisce il minore dei due parametri
Parameters
a
b
Returns
Definition at line 12 of file matematica.c.
int pred (int a)
Restituisce il precedente del parametro
Parameters
a
Returns
Definition at line 20 of file matematica.c.
Referenced by factorial().
int product (int a, int b)
Restituisce il prodotto dei due parametri Richiama la funzione sum
Parameters
a
b
Returns
Definition at line 57 of file matematica.c.
References get_product_b_major_zero(), and product().
Referenced by factorial(), and product().
int subtract (int a, int b)
Restituisce la differenza dei due parametri richiamando la funzione sum
Parameters
a
b
Returns
Definition at line 45 of file matematica.c.
References sum().
int succ (int a)
Restituisce il successivo del parametro
Parameters
a
Returns
Definition at line 24 of file matematica.c.
int sum (int a, int b)
Restituisce la somma dei due parametri Richiama le funzioni succe e pred
Parameters
a
b
Returns
Definition at line 40 of file matematica.c.
Referenced by get_product_b_major_zero(), and subtract().